# .travis.yml
language: node_js
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
node_js:
  - '5.11'
  - '6.2'
script: npm run travis
notifications:
  email: false
deploy:
  - provider: npm
    email: jim@vigour.io
    api_key: ${NPM_TOKEN}
    on:
      branch: master
      tags: true
